version: 2
jobs:
  build:
    docker:
      - image: phusion/baseimage:0.11
        environment:
          DEBUG_BUILD: true
          DEBIAN_FRONTEND: noninteractive

    working_directory: ~/straightedge

    steps:
      - checkout
      - run: apt-get update
      - run: ~/straightedge/scripts/init.sh

      # module test cases
      - run: source ~/.cargo/env && cd ~/straightedge && ./scripts/test.sh
